version: '3.8'

services:
  task-manager:
    build:
      context: ./bun-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bun-server:/app
      - /app/node_modules
    command: ["bun", "index.ts"]
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
